
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
class ArsivDuyurulari{
    private String duyuruarsiv;
    private String duyurukategori;
    private String duyurutarih;

    public ArsivDuyurulari(String duyuruarsiv, String duyurukategori, String duyurutarih) {
        this.duyuruarsiv = duyuruarsiv;
        this.duyurukategori = duyurukategori;
        this.duyurutarih = duyurutarih;
    }

    public String getDuyuruarsiv() {
        return duyuruarsiv;
    }

    public void setDuyuruarsiv(String duyuruarsiv) {
        this.duyuruarsiv = duyuruarsiv;
    }

    public String getDuyurukategori() {
        return duyurukategori;
    }

    public void setDuyurukategori(String duyurukategori) {
        this.duyurukategori = duyurukategori;
    }

    public String getDuyurutarih() {
        return duyurutarih;
    }

    public void setDuyurutarih(String duyurutarih) {
        this.duyurutarih = duyurutarih;
    }

    
    
}

    

/**
 *
 * @author EREN
 */
public class DuyuruOtomasyonu extends javax.swing.JFrame {

    private static ArrayList<ArsivDuyurulari> arsivDuyurulari = new ArrayList<ArsivDuyurulari>();

    public static ArrayList<ArsivDuyurulari> getArsivDuyurulari() {
        return arsivDuyurulari;
    }

    public static void setArsivDuyurulari(ArrayList<ArsivDuyurulari> arsivDuyurulari) {
        DuyuruOtomasyonu.arsivDuyurulari = arsivDuyurulari;
    }
    
    
    
    /**
     * Creates new form DuyuruOtomasyonuy
     */
    public DuyuruOtomasyonu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        duyuru_tablosu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ekle_button = new javax.swing.JButton();
        guncelle_button = new javax.swing.JButton();
        sil_button = new javax.swing.JButton();
        temizle_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        duyuru = new javax.swing.JTextField();
        kategori = new javax.swing.JComboBox<>();
        tarih = new javax.swing.JTextField();
        arsiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DUYURU İŞLEMLERİ OTOMASYONU");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        duyuru_tablosu.setBackground(new java.awt.Color(0, 102, 153));
        duyuru_tablosu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        duyuru_tablosu.setForeground(new java.awt.Color(255, 255, 255));
        duyuru_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DUYURU", "KATEGORİ", "TARİH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        duyuru_tablosu.setGridColor(new java.awt.Color(255, 255, 255));
        duyuru_tablosu.getTableHeader().setReorderingAllowed(false);
        duyuru_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duyuru_tablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(duyuru_tablosu);
        if (duyuru_tablosu.getColumnModel().getColumnCount() > 0) {
            duyuru_tablosu.getColumnModel().getColumn(0).setPreferredWidth(450);
        }

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        ekle_button.setBackground(new java.awt.Color(0, 153, 204));
        ekle_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ekle_button.setForeground(new java.awt.Color(255, 255, 255));
        ekle_button.setText("DUYURU EKLE");
        ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_buttonActionPerformed(evt);
            }
        });

        guncelle_button.setBackground(new java.awt.Color(0, 153, 204));
        guncelle_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        guncelle_button.setForeground(new java.awt.Color(255, 255, 255));
        guncelle_button.setText("DUYURU GÜNCELLE");
        guncelle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_buttonActionPerformed(evt);
            }
        });

        sil_button.setBackground(new java.awt.Color(0, 153, 204));
        sil_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sil_button.setForeground(new java.awt.Color(255, 255, 255));
        sil_button.setText("DUYURU SİL");
        sil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_buttonActionPerformed(evt);
            }
        });

        temizle_button.setBackground(new java.awt.Color(0, 153, 204));
        temizle_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        temizle_button.setForeground(new java.awt.Color(255, 255, 255));
        temizle_button.setText("TABLO TEMİZLE");
        temizle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizle_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ekle_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guncelle_button, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(sil_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(temizle_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guncelle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sil_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(temizle_button, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DUYURU:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KATEGORİ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TARİH:");

        duyuru.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        kategori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "GENEL", "ETKİNLİK", "ACİL!!!" }));

        tarih.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(duyuru, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kategori, 0, 0, Short.MAX_VALUE)
                            .addComponent(tarih, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(duyuru)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(tarih))
                .addGap(30, 30, 30))
        );

        arsiv.setBackground(new java.awt.Color(0, 153, 204));
        arsiv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arsiv.setForeground(new java.awt.Color(255, 255, 255));
        arsiv.setText("ARŞİV");
        arsiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arsiv, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arsiv, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel)duyuru_tablosu.getModel();

        if(duyuru.getText().trim().equals("") || kategori.getSelectedItem().equals("") || tarih.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Boş bırakılan yerleri doldurunuz. ");
        }
        else
        {
            Object[] eklenecek = {duyuru.getText(),kategori.getSelectedItem().toString(),tarih.getText()};

            model.addRow(eklenecek);
            duyuru.setText("");
            kategori.setSelectedIndex(0);
            tarih.setText("");
        }
    }//GEN-LAST:event_ekle_buttonActionPerformed

    private void guncelle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_buttonActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) duyuru_tablosu.getModel();

        int secili_row = duyuru_tablosu.getSelectedRow();

        if(secili_row == -1)
        {
            if(duyuru_tablosu.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(this, "Duyuru tablosu şu anda boş... ");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Güncellenecek duyuruyu seçiniz.");
            }
        }
        else
        {
            
            model.setValueAt(duyuru.getText(), secili_row, 0);
            model.setValueAt(kategori.getSelectedItem().toString(), secili_row, 1);
            model.setValueAt(tarih.getText(), secili_row, 2);

            JOptionPane.showMessageDialog(this, "Duyuru güncellendi...");
            

        }
    }//GEN-LAST:event_guncelle_buttonActionPerformed

    private void sil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) duyuru_tablosu.getModel();
        

        int secili_row = duyuru_tablosu.getSelectedRow();

        if(secili_row == -1)
        {
            if(duyuru_tablosu.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(this, "Duyuru tablosu boş.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Silinecek duyuruyu seçiniz.");
            }
        }
        else
        {
            String duyuruarsiv = (String) model.getValueAt(secili_row, 0);
            String duyurukategori = (String) model.getValueAt(secili_row, 1);
            String duyurutarih = (String) model.getValueAt(secili_row, 2);
            
            
            arsivDuyurulari.add(new ArsivDuyurulari(duyuruarsiv, duyurukategori, duyurutarih));
            model.removeRow(secili_row);
            
            JOptionPane.showMessageDialog(this, "Duyuru silindi.");
            duyuru.setText("");
            kategori.setSelectedIndex(0);
            tarih.setText("");

        }
    }//GEN-LAST:event_sil_buttonActionPerformed

    private void temizle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizle_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) duyuru_tablosu.getModel();
        
        
        model.setRowCount(0);
        
        duyuru.setText("");
        kategori.setSelectedIndex(0);
        tarih.setText("");
    }//GEN-LAST:event_temizle_buttonActionPerformed

    private void arsivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsivActionPerformed
        DuyuruArsivi duyuruArsivi = new DuyuruArsivi();
        
        duyuruArsivi.setVisible(true);
        duyuruArsivi.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_arsivActionPerformed

    private void duyuru_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duyuru_tablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) duyuru_tablosu.getModel();
        
        int secili_row = duyuru_tablosu.getSelectedRow();
        
        duyuru.setText(model.getValueAt(secili_row, 0).toString());
        kategori.setSelectedItem(model.getValueAt(secili_row, 1).toString());
        tarih.setText(model.getValueAt(secili_row, 2).toString());
    }//GEN-LAST:event_duyuru_tablosuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DuyuruOtomasyonu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DuyuruOtomasyonu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DuyuruOtomasyonu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DuyuruOtomasyonu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DuyuruOtomasyonu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arsiv;
    private javax.swing.JTextField duyuru;
    private javax.swing.JTable duyuru_tablosu;
    private javax.swing.JButton ekle_button;
    private javax.swing.JButton guncelle_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JButton sil_button;
    private javax.swing.JTextField tarih;
    private javax.swing.JButton temizle_button;
    // End of variables declaration//GEN-END:variables
}
